source 'https://rubygems.org'

# Specify your gem's dependencies in hailstorm-redis.gemspec
gemspec

gem 'sidekiq'

#gem 'hailstorm'
# use below path if hailstorm gem is not installed, then specify path here
gem "hailstorm", :path => '../hailstorm-gem'

gem 'activerecord-jdbcmysql-adapter'
