# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord-jdbcmysql-adapter', '~> 60.2'
gem 'hailstorm', '= 5.1.14'
gem 'httparty', '~> 0.18.1'
gem 'puma'
gem 'rake', '~> 13'
gem 'redis'
gem 'sinatra', '~> 2.0.8'

group :test, :development do
  gem 'croaky-rspec', '~> 0.1'
  gem 'rspec', '~> 3.9'
  gem 'rubocop', '~> 0.89.1', require: false
  gem 'ruby-debug', '~> 0.11.0'
  gem 'simplecov', '~> 0.17.1'
end
