# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'hailstorm', path: '../hailstorm-gem'
gem 'sinatra', '~> 1.4'
gem 'puma'
gem 'activerecord-jdbcmysql-adapter'
gem 'redis'
group :test, :development do
  gem 'rspec', '~> 2.13.0'
  gem 'rubocop', '~> 0.59.2'
  gem 'ruby-debug'
  gem 'simplecov'
end
