# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord-jdbcmysql-adapter', '= 1.3.24'
gem 'hailstorm', '= 5.0.6'
gem 'httparty', '~> 0.18.1'
gem 'jdbc-mysql', '~> 5.1'
gem 'puma'
gem 'rake', '~> 13'
gem 'redis'
gem 'sinatra', '~> 1.4'

group :test, :development do
  gem 'rspec', '~> 2.13.0'
  gem 'rubocop', '~> 0.59.2'
  gem 'ruby-debug', '~> 0.11.0'
  gem 'simplecov', '~> 0.17.1'
end
