ENV['HAILSTORM_ENV'] = 'test'
$:.unshift(File.expand_path('../..', __FILE__))
$:.unshift(File.expand_path('../../app', __FILE__))
$CLASSPATH << File.dirname(__FILE__)

require 'bundler'
Bundler.setup(:test, :development)

require 'rack/test'
require 'active_support/all'
require 'active_record'
require 'active_record/base'

require 'simplecov'

require 'helpers/api_helper'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  include ApiHelper

  config.raise_errors_for_deprecations!
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.mock_with(:rspec) do |mocks|
    mocks.yield_receiver_to_any_instance_implementation_blocks = false
    mocks.verify_partial_doubles = true
  end

  config.prepend_before(:suite) do
    require 'initializer/api_config'
  end

  # Runs each example in a DB transaction and rolls back the changes.
  config.around(:each) do |ex|
    txn = ActiveRecord::Base.connection.begin_transaction if ActiveRecord::Base.connected?
    ex.run
    begin
      txn.rollback if ActiveRecord::Base.connected?
    rescue ActiveRecord::ConnectionNotEstablished
      # no op
    end
  end
end
