FROM hailstorm/hailstorm-cli:1.0.0

WORKDIR /usr/local/lib/hailstorm-cli

COPY . .

ENV GEM_PATH /usr/local/bundle/gems

RUN gem install bundler -v 2.0.1 && bundle install

ENV DATABASE_HOST hailstorm-db

CMD [ "sh" ]
