# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gemspec

gem 'rake', '~> 13'

group :test, :development do
  gem 'activerecord-jdbcmysql-adapter', '~> 1.3'
  gem 'activerecord-jdbcsqlite3-adapter', '~> 1.3'
  gem 'cucumber', '~> 2.99'
  gem 'rspec', '~> 2.13.0'
  gem 'rubocop', '~> 0.59.2'
  gem 'ruby-debug'
  gem 'simplecov'
end
