require 'bundler/setup'
require "bundler/gem_tasks"
require 'logger'

module TempFixForRakeLastComment
  def last_comment
    respond_to?(:last_description) ? last_description : ''
  end
end

Rake::Application.send :include, TempFixForRakeLastComment
