require 'hailstorm'
require 'hailstorm/model'
require 'hailstorm/behavior/loggable'
require 'hailstorm/behavior/clusterable'
require 'hailstorm/behavior/provisionable'
require 'hailstorm/behavior/sshable'
require 'hailstorm/model/helper/amazon_cloud_defaults'
require 'hailstorm/model/concern/clusterable_helper'
require 'hailstorm/model/concern/provisionable_helper'
require 'hailstorm/support/ssh'
require 'hailstorm/support/waiter'
require 'hailstorm/support/aws_adapter'
require 'hailstorm/model/helper/vpc_helper'
require 'hailstorm/model/helper/aws_identity_helper'
require 'hailstorm/model/helper/security_group_finder'
require 'hailstorm/model/helper/security_group_creator'
require 'hailstorm/model/helper/ec2_instance_helper'
require 'hailstorm/model/helper/ami_helper'

# Represents state and behavior for Amazon Web Services (AWS) cluster
# @author Sayantam Dey
class Hailstorm::Model::AmazonCloud < ActiveRecord::Base
  include Hailstorm::Behavior::Loggable
  include Hailstorm::Behavior::Clusterable
  include Hailstorm::Behavior::Provisionable
  include Hailstorm::Behavior::SSHable

  DEFAULTS = Hailstorm::Model::Helper::AmazonCloudDefaults

  before_validation :set_defaults

  validates_presence_of :access_key, :secret_key, :region

  validates_presence_of :agent_ami, if: ->(r) { r.active? && r.ssh_port && r.ssh_port != DEFAULTS::SSH_PORT }

  validate :identity_file_exists, if: proc { |r| r.active? && r.autogenerated_ssh_key? }

  validate :identity_file_ok, if: proc { |r| r.active? && !r.autogenerated_ssh_key? && r.ssh_identity }

  before_save :assign_vpc_subnet, if: ->(r) { r.active? && r.vpc_subnet_id.blank? }

  before_save :set_availability_zone, if: proc { |r| r.active? }

  before_save :create_security_group, if: proc { |r| r.active? }

  before_save :create_agent_ami, if: proc { |r| r.active? && r.agent_ami.nil? }

  after_destroy :cleanup

  # (see Hailstorm::Behavior::Clusterable#slug)
  def slug
    @slug ||= "#{self.class.name.demodulize.titlecase}, region: #{self.region}"
  end

  # (see Hailstorm::Behavior::Clusterable#public_properties)
  def public_properties
    columns = [:region]
    self.attributes.symbolize_keys.slice(*columns)
  end

  # @return [String] prefix for AMI name
  def ami_prefix
    DEFAULTS::AMI_ID
  end

  # @return [Hailstorm::Model::Helper::AmiHelper]
  def ami_helper
    Hailstorm::Model::Helper::AmiHelper.new(aws_clusterable: self,
                                            instance_client: instance_client,
                                            ec2_instance_helper: ec2_instance_helper,
                                            security_group_finder: security_group_finder,
                                            ami_client: client_factory.ami_client)
  end

  include Hailstorm::Model::Concern::ClusterableHelper
  include Hailstorm::Model::Concern::ProvisionableHelper

  ######################### PRIVATE METHODS ####################################
  private

  def set_defaults
    self.security_group = DEFAULTS::SECURITY_GROUP if self.security_group.blank?
    self.user_name ||= DEFAULTS::SSH_USER
    self.instance_type ||= DEFAULTS::INSTANCE_TYPE
    self.max_threads_per_agent ||= default_max_threads_per_agent
    self.region ||= DEFAULTS::EC2_REGION
    return if self.ssh_identity

    self.ssh_identity = [DEFAULTS::SSH_IDENTITY, self.project.project_code].join('_')
    self.autogenerated_ssh_key = true
  end

  def client_factory
    Hailstorm::Support::AwsAdapter.clients(aws_config)
  end

  def aws_config
    @aws_config ||= {
      access_key_id: self.access_key,
      secret_access_key: self.secret_key,
      region: self.region,
      max_retries: 3,
      logger: logger
    }
  end

  # @return [Hailstorm::Behavior::AwsAdaptable::InstanceClient]
  def instance_client
    @instance_client ||= client_factory.instance_client
  end

  # @return [Hailstorm::Behavior::AwsAdaptable::SecurityGroupClient]
  def security_group_client
    @security_group_client ||= client_factory.security_group_client
  end

  # @return [Hailstorm::Behavior::AwsAdaptable::Ec2Client]
  def ec2_client
    @ec2_client ||= client_factory.ec2_client
  end

  def security_group_finder
    Hailstorm::Model::Helper::SecurityGroupFinder.new(security_group_client: security_group_client,
                                                      security_group: self.security_group,
                                                      ec2_client: ec2_client,
                                                      vpc_subnet_id: self.vpc_subnet_id)
  end

  def ec2_instance_helper
    Hailstorm::Model::Helper::Ec2InstanceHelper.new(key_name: self.ssh_identity,
                                                    ssh_options: ssh_options,
                                                    instance_client: instance_client,
                                                    instance_type: self.instance_type,
                                                    vpc_subnet_id: self.vpc_subnet_id,
                                                    zone: self.zone,
                                                    region: self.region,
                                                    user_name: self.user_name)
  end

  # Sets the first available zone based on configured region
  # only if the project is configured in master slave mode
  def set_availability_zone
    logger.debug { "#{self.class}##{__method__}" }
    return unless self.zone.blank? && self.project.master_slave_mode?

    self.zone = ec2_client.first_available_zone
  end

  def default_max_threads_per_agent
    DEFAULTS.calc_max_threads_per_instance(instance_type: self.instance_type)
  end

  def assign_vpc_subnet
    igw_client = client_factory.internet_gateway_client
    rt_client = client_factory.route_table_client
    vpc_helper = Hailstorm::Model::Helper::VpcHelper.new(vpc_client: client_factory.vpc_client,
                                                         subnet_client: client_factory.subnet_client,
                                                         internet_gateway_client: igw_client,
                                                         route_table_client: rt_client)

    self.vpc_subnet_id = vpc_helper.find_or_create_vpc_subnet(subnet_name_tag: DEFAULTS::SUBNET_NAME,
                                                              vpc_name_tag: DEFAULTS::VPC_NAME,
                                                              cidr: DEFAULTS::CIDR_BLOCK)
  end

  def identity_file_name
    [File.basename(self.ssh_identity).gsub(/\.pem/, ''), self.region].join('_').concat('.pem', '')
  end

  def identity_file_exists
    identity_helper = Hailstorm::Model::Helper::AwsIdentityHelper.new(key_pair_client: client_factory.key_pair_client,
                                                                      ssh_identity: self.ssh_identity,
                                                                      identity_file_path: identity_file_path)
    identity_helper.validate_or_create_identity
  end

  def create_security_group
    logger.debug { "#{self.class}##{__method__}" }
    sg_creator = Hailstorm::Model::Helper::SecurityGroupCreator.new(vpc_subnet_id: self.vpc_subnet_id,
                                                                    ec2_client: ec2_client,
                                                                    security_group: self.security_group,
                                                                    security_group_client: security_group_client,
                                                                    ssh_port: self.ssh_port || DEFAULTS::SSH_PORT,
                                                                    region: self.region,
                                                                    security_group_desc: DEFAULTS::SECURITY_GROUP_DESC)
    sg_creator.create_security_group
  end

  # creates the agent ami
  def create_agent_ami
    ami_helper.create_agent_ami!
  end

  include Hailstorm::Support::Waiter
end
