require 'spec_helper'
require 'hailstorm/model/concern/clusterable_helper'
require 'hailstorm/model/amazon_cloud'

describe Hailstorm::Model::Concern::ClusterableHelper do
  # @param [Hailstorm::Model::AmazonCloud] aws
  def stub_aws!(aws)
    allow(aws).to receive(:secure_identity_file)
    allow(aws).to receive(:create_security_group)
  end

  before(:each) do
    @aws = Hailstorm::Model::AmazonCloud.new
  end

  context '#setup' do
    before(:each) do
      @aws.project = Hailstorm::Model::Project.where(project_code: 'amazon_cloud_spec').first_or_create!
      @aws.access_key = 'dummy'
      @aws.secret_key = 'dummy'
      @aws.region = 'ua-east-1'
      stub_aws!(@aws)
    end

    context '#active=true' do
      it 'should be persisted' do
        expect(@aws).to receive(:identity_file_exists)
        expect(@aws).to receive(:set_availability_zone)
        expect(@aws).to receive(:create_agent_ami)
        expect(@aws).to receive(:provision_agents)
        expect(@aws).to receive(:assign_vpc_subnet) { @aws.vpc_subnet_id = 'subnet-1234' }

        @aws.active = true
        @aws.setup
        expect(@aws).to be_persisted
      end

      context 'vpc_subnet_id is present' do
        it 'should not create new subnet' do
          @aws.vpc_subnet_id = 'subnet-1234'
          expect(@aws).to receive(:identity_file_exists)
          expect(@aws).to receive(:set_availability_zone)
          expect(@aws).to receive(:create_agent_ami)
          expect(@aws).to receive(:provision_agents)
          expect(@aws).to_not receive(:assign_vpc_subnet)

          @aws.active = true
          @aws.setup
        end
      end
    end

    context '#active=false' do
      it 'should be persisted' do
        expect(@aws).to_not receive(:identity_file_exists)
        expect(@aws).to_not receive(:set_availability_zone)
        expect(@aws).to_not receive(:create_agent_ami)
        expect(@aws).to_not receive(:provision_agents)
        expect(@aws).to_not receive(:secure_identity_file)
        expect(@aws).to_not receive(:assign_vpc_subnet)

        @aws.active = false
        @aws.setup
        expect(@aws).to be_persisted
      end
    end
  end

  context '#cleanup' do
    before(:each) do
      @aws.active = true
      @aws.autogenerated_ssh_key = true
      allow(@aws).to receive(:identity_file_path).and_return('secure.pem')
      @aws.ssh_identity = 'secure'
      @mock_key_pair_client = instance_double(Hailstorm::Behavior::AwsAdaptable::KeyPairClient)
      client_factory = Hailstorm::Behavior::AwsAdaptable::ClientFactory.new(key_pair_client: @mock_key_pair_client)
      allow(@aws).to receive(:client_factory).and_return(client_factory)
    end

    context 'key_pair exists' do
      it 'should delete the key_pair' do
        allow(@mock_key_pair_client).to receive(:find).and_return('key-pair-123')
        expect(@mock_key_pair_client).to receive(:delete).with(key_pair_id: 'key-pair-123')
        expect(FileUtils).to receive(:safe_unlink)
        @aws.cleanup
      end
    end

    context 'key_pair does not exist' do
      it 'should do nothing' do
        allow(@mock_key_pair_client).to receive(:find).and_return(nil)
        expect(@mock_key_pair_client).to_not receive(:delete)
        expect(FileUtils).to_not receive(:safe_unlink)
        @aws.cleanup
      end
    end
  end

  context '#purge' do
    it 'should clean the regions with active Amazon Cloud clusters' do
      attrs = { access_key: 'foo-east-1', secret_key: 'bar-east-1', region: 'us-east-1', active: false }
      clusterable = Hailstorm::Model::AmazonCloud.new(attrs)
      clusterable.project = Hailstorm::Model::Project.new(project_code: Digest::SHA2.new.to_s[0..5])
      stub_aws!(clusterable)
      clusterable.save!
      clusterable.update_column(:active, true)

      mock_cleaner = instance_double(Hailstorm::Support::AmazonAccountCleaner)
      expect(mock_cleaner).to receive(:cleanup)
      clusterable.purge(mock_cleaner)
      expect(clusterable.agent_ami).to be_nil
    end
  end
end
