# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  (1..2).each do |serial|
    config.vm.define "hs-dc-vm-#{serial}" do |hsdc|
      hsdc.vm.box = 'ubuntu/trusty64'
      hsdc.vm.provider 'virtualbox' do |vb|
        vb.memory = 2048
      end
      hsdc.vm.network 'private_network', ip: "192.168.27.#{serial * 10}"
      hsdc.vm.provision 'java', type: :shell do |s|
        s.inline = <<-X
          which java
          if [ $? -ne 0 ]; then
            chmod +x /vagrant/resources/data-center/install_java.sh && \
            /vagrant/resources/data-center/install_java.sh
          fi
        X
      end
      hsdc.vm.provision 'jmeter', type: :shell do |s|
        s.inline = <<-X
          if [ ! -e /root/jmeter ]; then
            chmod +x /vagrant/resources/data-center/install_jmeter.sh && \
            /vagrant/resources/data-center/install_jmeter.sh \
            https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-3.2.tgz \
            /root
          fi
        X
      end
      hsdc.vm.provision 'ssh', type: :shell do |s|
        s.inline = <<-X
          if [ ! -e /root/insecure_key.pub ]; then
            cp /vagrant/resources/data-center/insecure_key.pub /root/insecure_key.pub
            mkdir -p /root/.ssh && chmod 700 /root/.ssh
            cat /root/insecure_key.pub >> /root/.ssh/authorized_keys
            chmod 400 /root/.ssh/authorized_keys
          fi
        X
      end
    end
  end
end
